
package ivlev.ivlevback._1c.exchangewithsites;

import ivlev.ivlevback._1c.commerceml_205.ObjectFactory;
import ivlev.ivlevback._1c.commerceml_205.КоммерческаяИнформация;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SiteExchangePortType", targetNamespace = "http://www.1c.ru/ExchangeWithSites")
@XmlSeeAlso({
    ObjectFactory.class,
    ivlev.ivlevback._1c.exchangewithsites.ObjectFactory.class
})
public interface SiteExchangePortType {


    /**
     * 
     * @param groupCode
     * @param modificationDate
     * @param organizationCode
     * @param warehouseCode
     * @return
     *     returns ru._1c.commerceml_205.КоммерческаяИнформация
     */
    @WebMethod(operationName = "GetAmountAndPrices", action = "http://www.1c.ru/ExchangeWithSites#SiteExchange:GetAmountAndPrices")
    @WebResult(targetNamespace = "http://www.1c.ru/ExchangeWithSites")
    @RequestWrapper(localName = "GetAmountAndPrices", targetNamespace = "http://www.1c.ru/ExchangeWithSites", className = "ru._1c.exchangewithsites.GetAmountAndPrices")
    @ResponseWrapper(localName = "GetAmountAndPricesResponse", targetNamespace = "http://www.1c.ru/ExchangeWithSites", className = "ru._1c.exchangewithsites.GetAmountAndPricesResponse")
    public КоммерческаяИнформация getAmountAndPrices(
        @WebParam(name = "ModificationDate", targetNamespace = "http://www.1c.ru/ExchangeWithSites")
        XMLGregorianCalendar modificationDate,
        @WebParam(name = "GroupCode", targetNamespace = "http://www.1c.ru/ExchangeWithSites")
        String groupCode,
        @WebParam(name = "WarehouseCode", targetNamespace = "http://www.1c.ru/ExchangeWithSites")
        String warehouseCode,
        @WebParam(name = "OrganizationCode", targetNamespace = "http://www.1c.ru/ExchangeWithSites")
        String organizationCode);

    /**
     * 
     * @param groupCode
     * @param modificationDate
     * @return
     *     returns ru._1c.commerceml_205.КоммерческаяИнформация
     */
    @WebMethod(operationName = "GetItems", action = "http://www.1c.ru/ExchangeWithSites#SiteExchange:GetItems")
    @WebResult(targetNamespace = "http://www.1c.ru/ExchangeWithSites")
    @RequestWrapper(localName = "GetItems", targetNamespace = "http://www.1c.ru/ExchangeWithSites", className = "ru._1c.exchangewithsites.GetItems")
    @ResponseWrapper(localName = "GetItemsResponse", targetNamespace = "http://www.1c.ru/ExchangeWithSites", className = "ru._1c.exchangewithsites.GetItemsResponse")
    public КоммерческаяИнформация getItems(
        @WebParam(name = "ModificationDate", targetNamespace = "http://www.1c.ru/ExchangeWithSites")
        XMLGregorianCalendar modificationDate,
        @WebParam(name = "GroupCode", targetNamespace = "http://www.1c.ru/ExchangeWithSites")
        String groupCode);

    /**
     * 
     * @param modificationDate
     * @return
     *     returns ru._1c.commerceml_205.КоммерческаяИнформация
     */
    @WebMethod(operationName = "GetOrders", action = "http://www.1c.ru/ExchangeWithSites#SiteExchange:GetOrders")
    @WebResult(targetNamespace = "http://www.1c.ru/ExchangeWithSites")
    @RequestWrapper(localName = "GetOrders", targetNamespace = "http://www.1c.ru/ExchangeWithSites", className = "ru._1c.exchangewithsites.GetOrders")
    @ResponseWrapper(localName = "GetOrdersResponse", targetNamespace = "http://www.1c.ru/ExchangeWithSites", className = "ru._1c.exchangewithsites.GetOrdersResponse")
    public КоммерческаяИнформация getOrders(
        @WebParam(name = "ModificationDate", targetNamespace = "http://www.1c.ru/ExchangeWithSites")
        XMLGregorianCalendar modificationDate);

    /**
     * 
     * @param itemID
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetPicture", action = "http://www.1c.ru/ExchangeWithSites#SiteExchange:GetPicture")
    @WebResult(targetNamespace = "http://www.1c.ru/ExchangeWithSites")
    @RequestWrapper(localName = "GetPicture", targetNamespace = "http://www.1c.ru/ExchangeWithSites", className = "ru._1c.exchangewithsites.GetPicture")
    @ResponseWrapper(localName = "GetPictureResponse", targetNamespace = "http://www.1c.ru/ExchangeWithSites", className = "ru._1c.exchangewithsites.GetPictureResponse")
    public byte[] getPicture(
        @WebParam(name = "ItemID", targetNamespace = "http://www.1c.ru/ExchangeWithSites")
        String itemID);

    /**
     * 
     * @param ordersData
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "LoadOrders", action = "http://www.1c.ru/ExchangeWithSites#SiteExchange:LoadOrders")
    @WebResult(targetNamespace = "http://www.1c.ru/ExchangeWithSites")
    @RequestWrapper(localName = "LoadOrders", targetNamespace = "http://www.1c.ru/ExchangeWithSites", className = "ru._1c.exchangewithsites.LoadOrders")
    @ResponseWrapper(localName = "LoadOrdersResponse", targetNamespace = "http://www.1c.ru/ExchangeWithSites", className = "ru._1c.exchangewithsites.LoadOrdersResponse")
    public Boolean loadOrders(
        @WebParam(name = "OrdersData", targetNamespace = "http://www.1c.ru/ExchangeWithSites")
        КоммерческаяИнформация ordersData);

}
